import Provider from "@/components/provider";
import Providers from "@/components/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_RESOURCE_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "bg-transparent flex items-center justify-center",
            inter.className
          )}
        >
          <Providers>
            <div className="w-[1400px] h-[1200px]">{children}</div>
          </Providers>
        </body>
      </html>
    </Provider>
  );
}
